### ISSUE TITLE
ply using float double value 

### ISSUE THREAD

**Issue by tarrabass** [keijiro/Pcx#10]
Thanks for this add ones, it's running perfectly but 
There are any chance that ply importer can read ply with float double value ?
thanks 
francois

**Comment by keijiro** [comment]
Could you provide a ply file that contains a minimum example of "ply with float double value"? Actually I'm not sure how it looks like.

**Comment by tarrabass** [comment]
https://drive.google.com/file/d/1z9ykExhosExjW22nsAq_iw6xjOdw5Ir0/view?usp=sharing
i guess it's a type conversion into the plyImporter, but it's to complicated for my level

Thanks for your amazing work, you make my life easier 
i did this video dance performance thanks to you 
https://vimeo.com/294511607

**Comment by keijiro** [comment]
I added double precision type support in v0.1.1.

https://github.com/keijiro/Pcx/releases/tag/v0.1.1

Note that it's converted to single precision when imported. It supports importing double precision data but there is no technical merit to use it.

I'm closing this issue now. Please feel free to reopen for further issues.

**Comment by matvol** [comment]
Thanks for your work! Big help!
Still I can't import ply with double precision floating ("unsupported property type 'propert float64 x'")
Any idea what might be the problem?

https://www.dropbox.com/s/s3y7czm5bglcuxl/LAZ_EXTRACT_CONVERTED_TO_PLY.ply?dl=0

**Comment by keijiro** [comment]
Thanks for pointing it out. I didn't know that there is another type name for double precision floating point numbers. I'll fix it later.

**Comment by keijiro** [comment]
This issue was fixed in [v0.1.3](https://github.com/keijiro/Pcx/releases/tag/v0.1.3).

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen again for further issues.
