### ISSUE TITLE
I can not import my point cloud file.

### ISSUE THREAD

**Issue by iceleaf97** [keijiro/Pcx#11]
I imported my .ply file. However I got the error message.
![image](https://user-images.githubusercontent.com/19263557/49009702-2dceda00-f1ac-11e8-9876-88a6eefc8443.png)

How could I solve this problem?

**Comment by davidthery** [comment]
Can you post also the header of your ply file ? Are you well using Binary little endian?

**Comment by keijiro** [comment]
This might be the same issue as #10. The current implementation of PCX doesn't support double precision. I'm thinking of adding it when I have time for this project.

**Comment by keijiro** [comment]
I added double precision type support in v0.1.1.

https://github.com/keijiro/Pcx/releases/tag/v0.1.1

Note that it's converted to single precision when imported. It supports importing double precision data but there is no technical merit to use it.

I'm closing this issue now. Please feel free to reopen for further issues.

**Comment by iceleaf97** [comment]
Thank you very much!
