### ISSUE TITLE
Can this support realtime streaming of point cloud ?

### ISSUE THREAD

**Issue by Rakiah** [keijiro/Pcx#12]
Hello, I was wondering if this system would work for realtime streaming of point cloud,

like a kinect/(lidare + camera) that is rendering in realtime in the unity scene ?

Thank you

**Comment by keijiro** [comment]
Thanks for the feedback. There are a few questions:

- Is Kinect still a thing? The production was discontinued. Now it's not available for the regular price in Japan. I'm not sure when it completely disappears from shelves.
- Is there a simple API to retrieve a point cloud from the sensor? I have no experience on Kinect, so I have no idea how difficult it is.

**Comment by Rakiah** [comment]
Hello @keijiro thanks for the quick response,
the kinect was just an example actually, what I mean is, would your renderer be able to compute in runtime point cloud without having very bad performance issue, would it be for example, able to take
[draco](https://github.com/google/draco/tree/master/unity) files in streaming and rearrange the generated mesh ? or is it just a shader rendering in a specific way a type of "mesh" if I can call it so

**Comment by keijiro** [comment]
Okay. Then, I have no clear answer. It sounds challenging but interesting.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
