### ISSUE TITLE
Shadow-Cast Support

### ISSUE THREAD

**Issue by benwwinn** [keijiro/Pcx#15]
All in the name. Any potential for feature to enable shadow casting or interaction with unity lighting at all?

**Comment by keijiro** [comment]
The disk shader support casting shadows.

**Comment by Levrden** [comment]
Hello !
I need the same too, but the disk shader is not working in HDRP
I assume i need to use the VfxGraph, but as i have a LOT of points, i need performance...Do you think that your shader is more efficient than if i use the shader graph ? 
BTW Thanks for this plugin, it's easier than using Houdini to convert

**Comment by keijiro** [comment]
> I assume i need to use the VfxGraph, but as i have a LOT of points, i need performance...Do you think that your shader is more efficient than if i use the shader graph ?

At first, please note that Shader Graph is different from VFX Graph.

Regarding performance comparison between VFX Graph and the disk shader, it's supposed that there is almost no significant difference between them. In some extreme cases, it could be slower. In some other cases, it could be faster. I'd recommend trying VFX Graph if it can be an option for your project.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
