### ISSUE TITLE
Cannot import my ply file

### ISSUE THREAD

**Issue by ECer23** [keijiro/Pcx#17]
Here's my ply file header

```
ply
format ascii 1.0
comment VCGLIB generated
element vertex 5841
property float x
property float y
property float z
property float nx
property float ny
property float nz
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 11678
property list uchar int vertex_indices
end_header
```

**Comment by keijiro** [comment]
As written in README, Pcx only supports PLY binary little-endian format at the moment. According to the file header, your ply file is exported in ASCII format. You have to convert it to the LE binary format or re-export it in the LE binary format.

**Comment by ECer23** [comment]
OK, thank you
