### ISSUE TITLE
Getting build error

### ISSUE THREAD

**Issue by Eytanm** [keijiro/Pcx#18]
After downloading repository and opening in various Unity versions, I still get errors:

Assets/Pcx/Editor/PlyImporter.cs(67,29): error CS1061: Type `UnityEditor.Experimental.AssetImporters.AssetImportContext' does not contain a definition for `AddObjectToAsset' and no extension method `AddObjectToAsset' of type `UnityEditor.Experimental.AssetImporters.AssetImportContext' could be found. Are you missing an assembly reference?

Can you please help me understand why is that?
The projects looks very cool 
Thanks!

**Comment by keijiro** [comment]
Which version of Unity are you trying? I recommend trying Unity 2018.3.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen if it still reproduces.
