### ISSUE TITLE
Ply not showing in scene

### ISSUE THREAD

**Issue by Glorfendal** [keijiro/Pcx#19]
Hi Keijiro,

While I have no issues importing my Ply file, when I drag it into the scene it simply does not show up. All of the components are there and editable, but I cannot see anything. The imported Ply file still has a thumbnail that is visible and shows my pointcloud

I downloaded the richmond-azaelias.ply file, and that works perfectly fine. However, both files are imported and visualised with no issues in Cloud Compare. I've included a screenshot of how it looks like after I drag in my Ply file (richmond-azaelias.ply in there for reference as working).

![Test](https://user-images.githubusercontent.com/48124412/55665076-a180a200-5884-11e9-808c-3beddee879e0.PNG)

As such it looks like it must be something to do with my Ply file; would you have any suggestions of what or how I may investigate further?

Any help would be very much appreciated.

(I am very very new to Unity, so my apologies if this question is very simple).

**Comment by keijiro** [comment]
Could you provide the file that causes the issue? I'd like to test it myself.

**Comment by keijiro** [comment]
I received test data from @Glorfendal and found that the point cloud lies too far from the origin. It's recommended to move them around the origin before exporting to avoid floating point precision error issues.

I'm closing this issue now. Please feel free to reopen for further questions.
