### ISSUE TITLE
Repo Setup

### ISSUE THREAD

**Issue by herman-nu** [keijiro/Pcx#20]
Hi Keijiro,

I'm curious about the layout of your repo and workflow when you use it in other projects. I see that you have a branch called `upm` and `master`. Why doesn't the upm branch include all of the files in the master branch? Notably I see the 'Asset' folder missing from the upm branch.

Could you point me to a project that uses this package with unity package manager?

**Comment by keijiro** [comment]
The `upm` branch is used to import the package via Unity Package Manager via the git integration. Please see the "Installation" section in [README.md](https://github.com/keijiro/Pcx/blob/master/README.md) to know how to use it.

This is just an experimental project but [PcxEffects2](https://github.com/keijiro/PcxEffects2) uses this feature to import PCX.

**Comment by keijiro** [comment]
Now I'm closing this issue. Please feel free to reopen for further questions.
