### ISSUE TITLE
Disk shader does not work in HDRP (2019.1.0f2)

### ISSUE THREAD

**Issue by sergiobd** [keijiro/Pcx#21]
Hi Keijiro, 

I tried the disk shader on HDRP in Unity 2019.1.0f2, I get the magenta shader of death (with no errors). Any idea why?
I have a volumetric capture of an actor as a sequence of vertex and colors lists (each frame has a list of vertices and a list of colors). Do you have a suggestion on how to render them apart from a geometry shader?

**Comment by keijiro** [comment]
Basically there is no compatibility in shaders between the legacy render pipeline and HDRP, so you can't simply use the PCX builtin shaders.

It might sound like a little bit strange idea but the Visual Effect Graph is the handiest way to visualize a point cloud on HDRP.

https://twitter.com/_kzr/status/1101395833541414912

Unfortunately, I have no time for writing a tutorial about the usage. Please check VFX Graph tutorials/articles. You can find some of them by googling.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
