### ISSUE TITLE
Why doesn't my ply file get imported as a mesh?

### ISSUE THREAD

**Issue by SubhajitAwe** [keijiro/Pcx#24]
Hi Kejiro,
Thanks for making this useful component. But, I am kinda unsure as to how it works when I add a new .ply file to my project. Does it automatically convert the file into a mesh? This new file is in little_big_endian format, I checked the header, so I think it should work, as you acknowledged in one of the other issues.
Thanks for your help,
Subhajit.
![Screen Shot 2019-06-21 at 1 24 20 AM](https://user-images.githubusercontent.com/51961948/59877367-5c6c0680-93c3-11e9-9225-abc8daf5c81b.png)

**Comment by keijiro** [comment]
It should work without any special effort. Is there any error message on the Console view?

**Comment by SubhajitAwe** [comment]
No, I don't see any errors in the Console. Someone helped me last night to edit one of these ply files. He said, it might be that the file is too lengthy, so he tried to truncate it and even sent me a trimmed mesh ply file. Even that file doesn't get converted.

**Comment by keijiro** [comment]
Could you share the original file? I'd like to look into it.

**Comment by SubhajitAwe** [comment]
Hi again,
I have attached the files. The ones starting with 118.. work, Meshtrim and 12... files don't work with PCX Importer.
Thanks for your help,
Subhajit.


[Archive.zip](https://github.com/keijiro/Pcx/files/3314629/Archive.zip)

**Comment by keijiro** [comment]
Thanks for providing them, but these files are successfully imported with pcx on my side.

![screenshot](https://i.imgur.com/gfJnRpA.png)

I'd recommend staring over from an empty new project.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen if it still reproduces.
