### ISSUE TITLE
Save the Color map

### ISSUE THREAD

**Issue by Levrden** [keijiro/Pcx#25]
Hello,
Is there a way to save and edit manually the color map texture generated for the vfx graph ?
I don't find any good way to edit colors properly inside the vfx graph
Thanks

**Comment by keijiro** [comment]
You have to modify the importer script to export the color map. For example, change this line

https://github.com/keijiro/Pcx/blob/master/Assets/Pcx/Runtime/BakedPointCloud.cs#L70

as follows

```
_colorMap.Apply(false, false); System.IO.File.WriteAllBytes("test.png", _colorMap.EncodeToPNG());
```

Then reimport the .ply file. `test.png` will be saved in the project directory..

**Comment by Levrden** [comment]
Thanks ! it works !
But when i reimport it as the colour map for my point cloud, the distribution is not the same
![Annotation 2019-06-28 105356](https://user-images.githubusercontent.com/24231978/60331140-45fe1600-9994-11e9-8454-97652e4adafc.png)
![Annotation 2019-06-28 105443](https://user-images.githubusercontent.com/24231978/60331141-45fe1600-9994-11e9-831a-590a54f02dc0.png)

I search for any compression or format error, but if you have an idea, i'll take it
Thanks

**Comment by keijiro** [comment]
I think you have to enable "Non-Power of 2" option in the texture importer settings.

**Comment by Levrden** [comment]
It was enabled, so i disabled it and that's it, it works ! Thanks a lot !
btw do you have any idea to tweak all the point cloud color, like sat, bright, contrast... ?

**Comment by keijiro** [comment]
You can do that by customizing the point cloud shader.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it or create a new issue for further questions.

**Comment by rvijgen** [comment]
Does this work for the position map as well? I successfully exported the position map, but I am unable to successfully load it back in again as it results in a distorted geometry.

This is the original position map
<img width="882" alt="Screenshot 2019-11-20 at 16 09 57" src="https://user-images.githubusercontent.com/1857817/69250614-49e33c80-0bb0-11ea-85f8-77be554866d8.png">

And this is what I get when I export the map to PNG and loading it back in again

<img width="890" alt="Screenshot 2019-11-20 at 16 09 20" src="https://user-images.githubusercontent.com/1857817/69250668-667f7480-0bb0-11ea-8d58-43059f1bec3c.png">

I am using the following texture import settings

<img width="538" alt="Screenshot 2019-11-20 at 16 10 15" src="https://user-images.githubusercontent.com/1857817/69250702-7303cd00-0bb0-11ea-8c68-8a2e57aa0cdf.png">

Any thoughts?

**Comment by keijiro** [comment]
@rvijgen 

> Does this work for the position map as well?

No, it doesn't. PNG only supports low dynamic range color, so values will be clipped by the range from 0.0 to 1.0 as like shown in your screen shot.

**Comment by rvijgen** [comment]
would there be any other way to export and edit the position data as an image (maybe a different file format)?

**Comment by keijiro** [comment]
I wonder if EncodeToEXR would be helpful.

https://docs.unity3d.com/ScriptReference/ImageConversion.EncodeToEXR.html

**Comment by rvijgen** [comment]
Yes, that works, thanks for your help!
