### ISSUE TITLE
example of pcx and vfx

### ISSUE THREAD

**Issue by Eytanm** [keijiro/Pcx#26]
Hi Keijiro! and all,
Unable to combine vfx and pcx in Unity. Is there an example project rendering pointcloud with vfx in unity?
Thanks for the amazing work!
Eytan

**Comment by keijiro** [comment]
I pushed an example to `vfxgraph-example` branch.

https://github.com/keijiro/Pcx/tree/vfxgraph-example

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.

**Comment by Eytanm** [comment]
Thanks!!!
