### ISSUE TITLE
real-time pointcloud update

### ISSUE THREAD

**Issue by Changliu52** [keijiro/Pcx#29]
Hi @keijiro 
Thank you for sharing the awesome code.
Im trying to use pcx for real-time visualisation of our continously updated pointcloud.
we update sourceBuffer when we get and updated pointcloud, but the unity doesn't seem to update the poincloud.

do we need to clean the cloud before updating the new one? if yes, how do we do it?

Many thank you in advance.

Chang

**Comment by keijiro** [comment]
It should work without any special process. Could you share a minimum project that can reproduce the issue?

**Comment by Changliu52** [comment]
```
using UnityEngine;
using Pcx;
using System;
using System.Collections;
using System.Collections.Generic;

public class PCLReader : MonoBehaviour
{
    public GameObject pclRenderer;
    //PointCloudRenderer cloud_renderer_;
    private PointCloudData cloud_ = null;

    List<Vector3> positions_ = new List<Vector3>();
    List<Color32> colors_ = new List<Color32>();
            

    
    public void Update()
    {
        positions_.Clear();
        colors_.Clear();

        // update pointcloud here

        cloud_.Initialize(positions_, colors_);
        var sourceBuffer = cloud_.computeBuffer;
        pclRenderer.GetComponent<PointCloudRenderer>().sourceBuffer = sourceBuffer;

    }
}
```

**Comment by keijiro** [comment]
Thanks for providing the additional information.

At the moment, `PointCloudData` doesn't support calling `Initialize` more than once. You have to recreate it every frame (instantiate and destroy it in every update). Although it's not a very efficient way, it should work.

**Comment by Changliu52** [comment]
Great to know. I will test it next week and report back.

**Comment by Changliu52** [comment]
Working with the update.

**Comment by mkl-b** [comment]
@Changliu52 
did you solved this problem?
Would you mind sharing?

**Comment by Changliu52** [comment]
I just call this every loop
cloud_ = null;
             cloud_ = new PointCloudData();
             cloud_.Initialize(positions_, colors_);		             cloud_.Initialize(positions_, colors_);
             print("A new cloud is updated!");
