### ISSUE TITLE
Disabling Billboarding in Disk Shader

### ISSUE THREAD

**Issue by ibilab** [keijiro/Pcx#32]
Hi, is there a way to disable the always facing camera billboarding int the disk shader? 

Thanks

**Comment by keijiro** [comment]
Try replacing `Disk.cginc` with this.

[Disk.zip](https://github.com/keijiro/Pcx/files/3629079/Disk.zip)

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.

**Comment by ibilab** [comment]
Thanks!
