### ISSUE TITLE
Texture2D

### ISSUE THREAD

**Issue by samuraishamploo** [keijiro/Pcx#33]
This work is really incredible. 

However, I would like to use Texture3D instead of Texture2D to use a plont cloud in the VFXgraph because with a Texture2D, all the points with a Z axis are baked in lines and not randomly as in a PLY file.

Do you know if it's possible to obtain a Texture3D from a point cloud in Unity ?

Thanks a lot.

**Comment by keijiro** [comment]
Sorry but I can't understand what you're going to do with 3D textures. Could you explain/rephrase your idea or provide references to related articles/papers.

**Comment by keijiro** [comment]
I'm closing this issue temporarily. Please feel free to reopen for further discussion.
