### ISSUE TITLE
Strange color range on Android

### ISSUE THREAD

**Issue by ChiefBreakeverything** [keijiro/Pcx#36]
Hi Keijiro,

I tried out the 'Plant' scene on Android 9 and got some strange results. The MeshRenderer version looks correct, but the Compute version seems to display with incorrect/greatly reduced color range. I tried changing the colorspace to Linear in the player settings but no luck.

![Screenshot](https://user-images.githubusercontent.com/4685982/66971305-6cc79000-f0dc-11e9-8d18-5cd921798762.png)

Using:
Unity 2019.2.9f1
Android 9 on Pixel 3 XL

**Comment by keijiro** [comment]
I think there is an issue with [`PcxDecodeColor`](https://github.com/keijiro/Pcx/blob/master/Assets/Pcx/Runtime/Shaders/Common.cginc#L15) on the device. I guess that the graphics driver or the shader compiler has an issue with integer arithmetic operations, but I can't research further on it as I don't have the device.

**Comment by ChiefBreakeverything** [comment]
Ah I see, thats fair. Thank you for the quick response, I'll try a few things and post back if I find anything.

**Comment by ChiefBreakeverything** [comment]
After a fair bit of fussing around, I managed to produce this:

`half3 PcxDecodeColor(uint data)
{
    data = ((data << 8) & 0xFF00FF00) | ((data >> 8) & 0xFF00FF);
    
    data = (data << 16) | (data >> 16);
    
    half b = (data >>  8) & 0xff;
    half g = (data >> 16) & 0xff;
    half r = (data >> 24) & 0xff;
    half a = (data >>  0) & 0xff;
    
    return half3(r, g, b) * a * PCX_MAX_BRIGHTNESS / (255 * 255);
}`

which seems to have fixed the problem. The colors get decoded properly on Android and still look the same in the Unity Editor for Windows as well (I haven't tried any other platforms besides these unfortunately). It isn't pretty, but hopefully it sheds some light on what might have been happening. 

Cheers!

**Comment by keijiro** [comment]
Whoa, I didn't expect that this kind of hack works. Thanks for the information. I'm thinking of reporting this as a shader compiler issue on Android.
