### ISSUE TITLE
Can i use this shader for point cloud in runtime? 

### ISSUE THREAD

**Issue by eisenWu** [keijiro/Pcx#37]
Hi @keijiro ,

i am newbee to shader, i am doing the projeck with rendering the point cloud in runtime, my first idea was using triangles and mesh to make visualization, but it seems using shader is a better solution if we consider the performance, so is that possible to realize it with shader?

best regards

Wei

**Comment by keijiro** [comment]
Using a shader might be a better solution for your problem, but the shaders in this project is specially designed for data imported via the Pcx importer, so I hardly think that it's useful for your project.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
