### ISSUE TITLE
Newbie question: how to integrate Pcx with unity

### ISSUE THREAD

**Issue by melkishengue** [keijiro/Pcx#39]
Hello @keijiro ,

thanks for sharing this awesome library. Do you have any ressource explaining how to integrate Pcx with Unity to display pointcloud points generated from ros ? Any advice would be welcome as well.

I already imported the project into unity as specified in the installation guidelines.

Thanks again.

**Comment by keijiro** [comment]
I have no idea what ros is, so there is no knowledge I can provide for it.

**Comment by sergiobd** [comment]
@melkishengue, try to export a .PLY from your ROS application and then use the repo as instructed.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by wes-kay** [comment]
Sorry to Necro, hopefully this helps others looking how to import ply into the scene: @melkishengue https://github.com/keijiro/Pcx/issues/100
