### ISSUE TITLE
Can the Point Size automatic change with the distance between the camera?

### ISSUE THREAD

**Issue by eisenWu** [keijiro/Pcx#40]
Hallo @keijiro ,
your shader works really good, appreciate it.
Is it possible to change the point size automaticly depend on the distance between the camera? i meam in real time.
What i want it to be, if the point is far away of the camera then it should bigger than the point near the camera.
Thanks in advance.

**Comment by keijiro** [comment]
> What i want it to be, if the point is far away of the camera then it should bigger than the point near the camera.

This is quite different from the standard implementation of perspective. There is no plan to add such a unique feature.

This issue tracker is not a place for consulting individual projects. I'm closing this issue ticket as the question is irrelevant to the Pcx project.

I want to give a small hint for you: The sizes of points are calculated in the following line. You can change the behavior by modifying it.

https://github.com/keijiro/Pcx/blob/master/Assets/Pcx/Runtime/Shaders/Point.shader#L78
