### ISSUE TITLE
Mesh not readable

### ISSUE THREAD

**Issue by sergiobd** [keijiro/Pcx#41]
Hi Keijiro,

I've used this asset extensively using the texture baked import settings. For my current application  I need to use a mesh. I use the "mesh" container type in the import settings. However, when I try to access the mesh data (vertices and colors) via a script, Unity complains it is not readable, which I cant set in the inspector.  Any clues?

Best,

Sergio

**Comment by sergiobd** [comment]
Ok, I think I got it. You are marking the mesh at not readable in line 180 of the mesh importer, right?

**Comment by keijiro** [comment]
Yes. Try changing it to false.

**Comment by sergiobd** [comment]
Thanks!
