### ISSUE TITLE
Rending just on one HoloLens Display

### ISSUE THREAD

**Issue by MarcoHolo** [keijiro/Pcx#43]
While using this Lib in a HoloLens-project, built with Unity, I can see the rendering of the point-cloud just on the left display. On the right eye there is no rending. We are using HoloLens Generation 1 here. We tested with multiple devices - same behaviour. 

Add this info:
I'm using the Point Cloud Renderer with Container-Type "ComputeBuffer"

**Comment by keijiro** [comment]
Just for your information: I've never tested Pcx with VR/AR devices. Personally, I don't have any XR device at the moment, so please don't expect that this issue would be solved very soon. I'd like to solve the problem when I have time, but please note that it'll be done for URP (Universal Render Pipeline) or HDRP, not for the legacy render pipeline.

**Comment by afauch** [comment]
@MarcoHolo Have you tried enabling multi-pass rendering? Will slow performance, but for me this enabled stereoscopic viewing of the point cloud.

Project Settings > Player > XR Settings > Stereo Rendering Mode > Multi Pass

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further problems.
