### ISSUE TITLE
Upm branch

### ISSUE THREAD

**Issue by jbltx** [keijiro/Pcx#45]
Hello,
Sorry for the disturbance, but I was wondering how do you create your `upm` branch ? It seems to be a symbolic link to the `Assets/pcx` folder and I think this git feature should be really useful (this is a nice example) , I have never seen this before !

But maybe you just created another normal branch and put everything into it. 😄

Thank you in advance for the information !

**Comment by keijiro** [comment]
> But maybe you just created another normal branch and put everything into it.

This is what I did to the branch.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further problems.
