### ISSUE TITLE
Forming polygons from points?

### ISSUE THREAD

**Issue by Bradyk27** [keijiro/Pcx#47]
Curious if any work had been done on forming polygons from points to make a true 3D object? Also, on a (possibly) related note, how does one use Texture2D? Fairly new to unity and this is fantastic work, so I appreciate the help very much.

**Comment by Bradyk27** [comment]
As a follow up--I've setup a unity project with VFX Graph capabilities, and have found where I can apply a position & texture map to a point cloud cache file. The problem is my .ply fails to convert through the default point cloud cache bake because it's not made of triangles. Not sure if this is what I'm looking for exactly, but any thoughts?

**Comment by keijiro** [comment]
You should look for a program that has the capability to reconstruct a mesh from a point cloud. That is a quite complicated technique. Pcx is just a small utility plugin. Please don't expect that it can handle things like that.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
