### ISSUE TITLE
Add point cloud data failed due to MonoBehaviour

### ISSUE THREAD

**Issue by glennliu** [keijiro/Pcx#50]
Hi 

I import the Pcd package and tried to render point cloud in following steps, 
- Import Pcx packages.
- Create _PcxRender_ Gameobjects.
- Drag script _/Assets/Pcd/Runtime/PointCloudData.cs_ into object _PcxRender_

It showed errors as below,
![ssss](https://user-images.githubusercontent.com/8009679/80196654-47e64380-8650-11ea-991c-5eda64acdb43.PNG)

Can you give advice with that?

Thanks

**Comment by keijiro** [comment]
PointCloudData is not a MonoBehaviour class, so you can't add it to a game object as a component.

I'd recommend checking tutorials like this one: https://www.youtube.com/watch?v=aKfPUCZYAhw

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
