### ISSUE TITLE
Continuous update a point cloud map from a flying drone

### ISSUE THREAD

**Issue by glennliu** [keijiro/Pcx#51]
Hi

My question in #50 is well solved. Thanks for your advice.

I realized the package currently draws a static point cloud map for one time. But in my case, I need to draw a point cloud map continuously. The point clouds are updating in real-time. Does this package has the function? 

Besides, I noticed the package used **Graphics.DrawProcedural** to draw each geometry. I'm not sure is it gonna affect the rendering performances if I draw up to 50,000 point clouds at 1Hz.

The device I'm using is HoloLens1. 

Thanks
Glen

**Comment by keijiro** [comment]
> Does this package has the function?

No. Pcx is just an importer for .ply files. Real-time point cloud is out of the scope.

I think Rsvfx is a better example that is closer to your idea.

https://github.com/keijiro/Rsvfx

https://twitter.com/_kzr/status/1133300004674609153

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by glennliu** [comment]
> > Does this package has the function?
> 
> No. Pcx is just an importer for .ply files. Real-time point cloud is out of the scope.
> 
> I think Rsvfx is a better example that is closer to your idea.
> 
> https://github.com/keijiro/Rsvfx
> 
> https://twitter.com/_kzr/status/1133300004674609153

will try with Rsvfx. Thanks!
