### ISSUE TITLE
Visual effect graph managing total point count

### ISSUE THREAD

**Issue by Reddevildragg** [keijiro/Pcx#52]
Is there a way with the visual effect graph to have the total points only counting what the camera can see. From what I can tell from looking if I set a point count then this also counts to the points behind the camera/would not be visible and as such takes detail away from where the focus could be. Any idea what would be used to change this?
Thanks

**Comment by keijiro** [comment]
As far as I know, there is no such an option as a visible point count with VFX Graph. I'd recommend using the VFX Graph forum for further questions.
