### ISSUE TITLE
How do I create Position map and Color map for the vfxgraph?

### ISSUE THREAD

**Issue by VessoVit** [keijiro/Pcx#56]
First I want to say thanks for your contribution to the community, love 

I used Metashape to create a model I want to use. Importing it in Unity with Pcx works fine, but I'm not getting any color map and position map like the model you showed in the vfxgraph example. Can you please elaborate how can we create such so we can use the model in VFX?

**Comment by keijiro** [comment]
Use Texture Container Type: https://github.com/keijiro/Pcx/blob/master/README.md

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
