### ISSUE TITLE
Crashes on 2019.4.8f1

### ISSUE THREAD

**Issue by Zumbalamambo** [keijiro/Pcx#57]
I cloned this repo and tried to open with Unity 2019.4.8f1.

However, the Unity is crashing for some reason. Any possible fixes? I use Ubuntu

**Comment by keijiro** [comment]
Could you try 2019.4.9?

This is not relevant to Pcx, but the recent versions of Unity 2019.4 have a crash issue with Vulkan. This issue was fixed in the latest version.
