### ISSUE TITLE
Accessing the full path of the 2D texture of a PLY

### ISSUE THREAD

**Issue by Bjerken** [keijiro/Pcx#58]
Hi!
I am moving this question to this repository.
I am trying to access the path of the Position map and Color maps (The 2D textures) of a PLY. I can only seem to access the path of the PLY itself. Though it is possible to access the 2D textures through the graph editor. Do you have any solution?

**Comment by keijiro** [comment]
> Do you have any solution?

No. You can't access embedded assets using a file path.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by Bjerken** [comment]
Is there any other way of accessing it through a script?

**Comment by keijiro** [comment]
https://docs.unity3d.com/ScriptReference/AssetDatabase.LoadAssetAtPath.html

**Comment by Bjerken** [comment]
Thank you!
