### ISSUE TITLE
impossible to edit the pcx settings

### ISSUE THREAD

**Issue by wmathilde** [keijiro/Pcx#60]
Hello,

I don't know if this is a problem with my Unity settings, but I cannot edit the parameters of the plugin.
Every editor is greyed out in Unity like below (Default Point and PCX.editor for example). I have searched in the scripts that define the editors but did not find anything that would cause the content to be non-modifiable.
![image](https://user-images.githubusercontent.com/71834290/96988712-fa766080-1524-11eb-8926-a06c2f963146.png)

Would you know how to solve this problem?

Thank you for your time

**Comment by keijiro** [comment]
You can't modify the default material asset. Create a new material and use it instead.
