### ISSUE TITLE
2020.2 compatability

### ISSUE THREAD

**Issue by sjaakjules** [keijiro/Pcx#61]
The unity assetImporters are no longer experimental.

You should change using to something like: (if i have my versions correct which i prob dont.

#if UNITY_2020_2_OR_NEWER
using UnityEditor.AssetImporters;
#elif UNITY_2018_4_OR_NEWER
using UnityEditor.Experimental.AssetImporters;
#endif

**Comment by keijiro** [comment]
Fixed in 1.0.1.
