### ISSUE TITLE
Creating VFX Graph

### ISSUE THREAD

**Issue by Zumbalamambo** [keijiro/Pcx#63]
I have managed to import the pointcloud with pcx and converted the container type to VFX. But the model is not being shown when  I tried to create a pcache file. how can I fix this?

**Comment by keijiro** [comment]
It doesn't use a pcache file. Please check the vfxgraph-example branch that contains a sample VFX Graph. 
https://github.com/keijiro/Pcx/tree/vfxgraph-example

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
