### ISSUE TITLE
shader doesn't work for hdrp

### ISSUE THREAD

**Issue by jinialadin1** [keijiro/Pcx#64]
your asset works excellent in unity 2019.4
I tried to upgrade my project into hdrp 7.5 but shader doesn't works.
HD camera doesn't render the point cloud object but I could see it in editor.

![image](https://user-images.githubusercontent.com/16120321/108188643-28765500-7153-11eb-95e0-467c9ca9b991.png)
I checked every camera components to render the point cloud but it doesn't work.

Do you have any plan for make shader works with HDRP?
Thanks a lot

**Comment by keijiro** [comment]
Please check #21

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
