### ISSUE TITLE
[Issues] The VFX point desapears if don't have the correct rotation

### ISSUE THREAD

**Issue by Fenikkel** [keijiro/Pcx#65]
Seems that the VFX graph using the point cloud doen't render if don't have the "correct" point of view.
In my case, seems that if the z axis of the point cloud it's not aligned with the camera, this vfx it's not rendered. Even in the editor "scene".

**Comment by keijiro** [comment]
Use the orientation block with the FaceCameraPlane/FaceCameraPosition options.

https://docs.unity3d.com/Packages/com.unity.visualeffectgraph@6.9/manual/Blocks.html#orientation-blocks

**Comment by keijiro** [comment]
I'm closing this issue as irrelevant (this is not a question about Pcx but general use of VFX Graph). Please feel free to reopen it for further problems.

**Comment by Fenikkel** [comment]
I resolved the problem.
This is the solution in the case you are using planes as output: _Use the orientation block with the FaceCameraPlane/FaceCameraPosition options._

But I was using "Lit Cubes" as output. So, **the problem was in the point cloud pivot**. When it goes out of the camera fustrum, the particle system disapears.

So, in the case you are using Sketchfab point clouds and the pivot is not in the center, you can edit it with a blender plugin. 
I followed this tutorial to do that: [Point cloud visualizer](https://youtu.be/eXct_7k779Q)

Anyway, as Kejiro said, this issue is irrelevand for the project.

**Comment by keijiro** [comment]
In that case,  you can extend the bounding box to avoid being culled. Use the Bounds property in the Initialize context.

https://docs.unity3d.com/Packages/com.unity.visualeffectgraph@11.0/manual/Context-Initialize.html
