### ISSUE TITLE
Lit Disc-Shader

### ISSUE THREAD

**Issue by walkinghome** [keijiro/Pcx#69]
Hey Keijiro. 

Thanks for your awesome work and support on GitHub. 
Is there a way to make the particles lit? We are using the disc-shader inside the URP.

Unity Version 2019.4.17f1

Best
Vincent

**Comment by keijiro** [comment]
You have to modify the shader. If you're not familiar with shader coding, it's recommended to use VFX Graph + Shader Graph instead.
