### ISSUE TITLE
WebGL support and V-PCC

### ISSUE THREAD

**Issue by jhynes94** [keijiro/Pcx#70]
Hello keijiro,

I've been using your tool and loving it. It works super well.

I've run into a slight issue where I cannot render it via my browser with WebGL.

Do you have any recommendations / will this be supported at a later time? Also will you offer the ability to process V-PCC?
https://github.com/nokiatech/vpcc

Best,

Justin

![Capture](https://user-images.githubusercontent.com/5491647/118345654-06972f00-b504-11eb-957d-55e5da8fe4c7.PNG)

**Comment by keijiro** [comment]
You can use the `Point Cloud/Point` shader instead.

**Comment by keijiro** [comment]
I don't know what V-PCC is, but it seems that there is no relevance between .ply and V-PCC. So, I have no comment.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
