### ISSUE TITLE
UPM package 

### ISSUE THREAD

**Issue by haitheredavid** [keijiro/Pcx#73]
Hihi 👋🏻 I've been trying to reference the upm package for pcx but the package is currently not available due to build errors, looks like an issue with synced tags... Is it possible to have this build updated for a simple soul like myself to reference it as a dependency?

**Comment by keijiro** [comment]
I'm pretty sure that there isn't any issue with npm.js. Could you re-check the instruction described in the "How to install" section?

If you still have issues with it, please copy-paste error messages.

**Comment by haitheredavid** [comment]
Thanks for response. I re-visited the "how to install" section but I didn't see a solution to my issue. I just want to clarify that I'm building a OpenUPM package that lists `"jp.keijiro.pcx": "1.0.1"` as a dependency within my `package.json`. I can successfully reference the pcx package in my local project since I have it added to my scoped registry, but when I add my upm package to a new project it does not add pcx too... I am a bit new to upm so I tried looking into adding a scooped registry to my `package.json` but it [seems like that is not possible](https://forum.unity.com/threads/scoped-registry-in-package-json-not-working.868831/).

Ah, something I should also clarify is my reference to your pcx project on upm. I was seeing that pcx was stored on upm but has [always had failed builds](https://openupm.com/packages/jp.keijiro.pcx/?subPage=pipelines), but I didn't realize that someone else setup this package. Apologies, I should of checked this before.

**Comment by keijiro** [comment]
First of all, I have never used OpenUPM. So, I have no idea about what happening on the OpenUPM side.

If you want to solve problems with the Pcx package on OpenUPM, please contact the maintainer.
