### ISSUE TITLE
How can I use this to render pointcloud stream

### ISSUE THREAD

**Issue by eternity123-null** [keijiro/Pcx#75]

**Comment by eternity123-null** [comment]
I want to render pointcloud real-time in Unity ,can I use this package?

**Comment by keijiro** [comment]
You can render static point clouds, but it can't handle a point cloud stream.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by eternity123-null** [comment]
thank you very much！
