### ISSUE TITLE
SV_VertexID semantic is not supported on GLES 2.0 at line 17 (on gles)

### ISSUE THREAD

**Issue by PacsoftIta** [keijiro/Pcx#76]
Hi, I'm trying to build an app for android using your plugin. I'm getting this error everytime I put in the scene my point cloud (binary / little endian).  Could you help me?

**Comment by keijiro** [comment]
As noted on README, the disk shader requires the geometry shader feature (GLES2.0 doesn't support it).

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
