### ISSUE TITLE
Shader - .ply in pink

### ISSUE THREAD

**Issue by armstrong0919** [keijiro/Pcx#77]
Hi Keijiro

Really thank you for your awesome work.
it's really really helpful.

I tried this project in Unity 2019.4
But shader is in pink.
Should I do something to deal with it?

![1638962213683](https://user-images.githubusercontent.com/64424751/145199922-9f679909-c8b5-4522-9f19-7e998f9555c8.jpg)

**Comment by keijiro** [comment]
Which shader are you using? Which platform are you using? Which GPU are you using?  Does your GPU supports the shader?

**Comment by armstrong0919** [comment]
Hi keijiro
I'm sorry for this stupid question.
Because the problem is my GPU(Intel HD Graphics 5000) which is not support the shader.
And I use another PC(GeForce 1060) to test. The result is successful.

Thank you for reply.

**Comment by keijiro** [comment]
Okay. I'm closing this issue.
