### ISSUE TITLE
Disk shader issue

### ISSUE THREAD

**Issue by dvdsmthdvd** [keijiro/Pcx#78]
Point shader works well, but I get a pink texture when I choose the disk shader. I'm not an expert with Unity shaders, but is this a package problem or something else?

**Comment by keijiro** [comment]
The disk shader requires geometry shader support. Please check if your device supports geometry shaders.

(Hint: It's not supported on most platforms but on DX11)

**Comment by dvdsmthdvd** [comment]
Thank you so much for the reply. I’ve tried DX11 but it didn’t work. Still getting pink materials using the disk shader. Maybe an HDRP issue.
________________________________

**Comment by dganzella** [comment]
Yeah I have the same issue. It works on The Custom PointCloudRenderer but for some reason it gets magenta when trying to use with mesh. (Windows/DirectX)

The point shader works, its just the disk shader + mesh that does not.
