### ISSUE TITLE
Particles disappears when looked at from a specific direction. 

### ISSUE THREAD

**Issue by PockPocket** [keijiro/Pcx#79]
Hi, do you know why my particles disappears when I move my camera in these specific ways (see video below) ? This happens in both the scene view and the game view from the camera. Also some kind of LOD banding effect seems to be obstructing the particles when looking from afar. Thanks alot !

https://drive.google.com/file/d/1VWsVgMt_cKWp13tWjQ0j_z3IlZOzMJ7t/view?usp=sharing

Mathieu.

**Comment by keijiro** [comment]
Are you using VFX Graph? It seems that the VFX system is culled. You can extend the bounds to void being culled.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.

**Comment by PockPocket** [comment]
THANKS
