### ISSUE TITLE
can this manipulate each point by c#?

### ISSUE THREAD

**Issue by leaf918** [keijiro/Pcx#8]

**Comment by keijiro** [comment]
At the moment, I'd say it's not practical. Manipulating points from C# can be 1,000 times slower than shader.

In the near future, it will become practical by utilizing the C# job system and the Burst compiler. I'll give them a try then.

**Comment by leaf918** [comment]
using GPU drawmeshinstance may fix my problem ,thanks.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
