### ISSUE TITLE
What is point size dependent upon?

### ISSUE THREAD

**Issue by wes-kay** [keijiro/Pcx#82]
I'm not able to modify the size on my device, I understand "Only some platforms support point size properties" but what does that mean? If I was to build out with a point size of 1 does that mean that a device that supports it will render it at 1 in size?
This is all I'm able to see:
![image](https://user-images.githubusercontent.com/40011470/175449975-c19df6a7-1076-4a13-8c35-a17b7fad8ef7.png)

**Comment by keijiro** [comment]
That depends on the case. It may work on iPhone (Metal), but I'm not sure about Android (Vulkan).
