### ISSUE TITLE
Point Size properties : Compatibility Check

### ISSUE THREAD

**Issue by PockPocket** [keijiro/Pcx#83]
![image](https://user-images.githubusercontent.com/73412598/175789719-f3c8a598-652e-4dcc-bf4e-47970ba33dec.png)

Hi,

My Point Size Value dosen't seems to work. I'm trying to see if my version of Unity (2019.4.8f1) allows me to execute this operation but I can't seem to find where in the script the value should be set to 0. 

What the PointCloudRender scripts:
![image](https://user-images.githubusercontent.com/73412598/175789807-13b39739-a311-4def-8514-7e8f9ea3f37c.png)

![image](https://user-images.githubusercontent.com/73412598/175789828-7053245a-3f51-4496-ac4b-03d812ae2b4b.png)

Any input on that topic would be truly appreciated.

Thanks!
Mathieu.

**Comment by keijiro** [comment]
Which platform (Graphics API) are you using? DX11 on Windows?

**Comment by PockPocket** [comment]
Direct3D11 on Windows.

**Comment by keijiro** [comment]
As noted on README, it doesn't work on DX11.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
