### ISSUE TITLE
Can't take pictures in Hololens

### ISSUE THREAD

**Issue by 159chenJie159** [keijiro/Pcx#84]
I try to render point cloud in HoloLens, Pcx can get a good rendering effect, but when I take a photo, there is no point cloud in the photo. This is because the shader used by HoloLens is "MixedRealityStandard.shader", while the one used by Pcx is "Point.shader". I tried to modify it, but the two seem to be incompatible, is there any solution?

**Comment by keijiro** [comment]
The short answer is no. You have to rewrite the shader.

I have no idea how to modify it as I don't have any experience on HoloLens.
