### ISSUE TITLE
PCX with MacBook M1 Arm Chip 

### ISSUE THREAD

**Issue by Dennis123121x2** [keijiro/Pcx#86]
Does anyone have experience with the pcx package and the "new" Mac Arm Chips? 

I'm using an M1 MacBook Pro and struggling to get the same performance as before with the older version.
Any tips and tricks? Any setting I've missed? 

Thanks
<img width="2002" alt="Bildschirmfoto 2022-08-01 um 20 52 11" src="https://user-images.githubusercontent.com/16954347/182222395-f7e95181-63ff-48de-ad5b-0fa188371a70.png">
!

**Comment by keijiro** [comment]
There is no known issue with M1/M2 Mac.

Unfortunately, it's not clear what's happening on your side from your screenshot.

You can submit a bug report to Unity using Bug Reporter if you find any problem with Unity.

**Comment by keijiro** [comment]
I'm closing this issue as not reproducible. Please reopen it for further problems.

**Comment by Dennis123121x2** [comment]
thanks!
