### ISSUE TITLE
unity extremely lag and slow

### ISSUE THREAD

**Issue by Morrisssss** [keijiro/Pcx#87]
<img width="1440" alt="截圖 2022-08-15 下午10 57 04" src="https://user-images.githubusercontent.com/82313155/184661519-ddb2b008-d563-4469-867e-0c47ae106bb5.png">
<img width="1440" alt="截圖 2022-08-15 下午10 49 47" src="https://user-images.githubusercontent.com/82313155/184661530-5ee97d50-caae-437b-98a7-15f62f20a9f0.png">

I've import my ply point cloud model into Unity.
It's a model of alley. As you can see in the pictures above.

But after I import the model, Unity became extremely lag.
I can't even move my cursor.

My computer is M1 macbook air, and it got 16gb ram.
Its ability should be good enough.

Is the model data too big for my computer?
How can I fix this problem?
I tried to change the project setting. 
I changed the quality into very low, but It doesn't help.

<img width="1440" alt="截圖 2022-08-15 下午10 58 08" src="https://user-images.githubusercontent.com/82313155/184664197-64ec4266-fa9d-4d45-94fd-471855fb1b11.png">

Can you help me?
Thank you so much.

**Comment by keijiro** [comment]
How many points in the point cloud?

**Comment by Morrisssss** [comment]
It supposed to be Ten million points.
but I don't know the differences between tie points and points.

I shot a screenshot.

<img width="1440" alt="截圖 2022-08-16 上午12 45 08" src="https://user-images.githubusercontent.com/82313155/184680358-d91f8d12-0273-4fef-9885-01d0701d9fae.png">

thank so much for your help

**Comment by keijiro** [comment]
You can inspect the real point count on Unity Editor.

**Comment by Morrisssss** [comment]
<img width="1440" alt="截圖 2022-08-16 下午6 04 15" src="https://user-images.githubusercontent.com/82313155/184853834-b9191307-fecb-498d-9b56-65e41c08dd9e.png">

Sorry, I can't find the point count in Unity.
Could you tell me the position of the point count?

Thanks so much for your help.

**Comment by keijiro** [comment]
Press "▶️" on the .ply file asset and select a mesh object in it.

**Comment by Morrisssss** [comment]
thanks a lot
I find it
It have Ten million points.

<img width="1440" alt="截圖 2022-08-16 下午10 00 46" src="https://user-images.githubusercontent.com/82313155/184899530-ff88284c-fbd3-4d3c-9e51-da821ed1942e.png">

**Comment by keijiro** [comment]
Simply saying, 10 million is too much. I'd recommend reducing points.

**Comment by Dennis123121x2** [comment]
I think this is the same issue as: PCX with MacBook M1 Arm Chip #86 – which I posted last summer. I still have not resolved it. On my MacBook Pro 2019 the pcx runs very smoothly, handling up to 200 mio points (decided into different ply files) Each up to 40mio point. So very impressive numbers. The Arm M1 Chip MacBook from early 2022 with 32gb ram falls way behind. 

The screenshots of this post are very much comparable to my situation. Is the pcx plugin working on the graphics card/gpu which is missing in the new arm architecture? 

It would be great to find a solution for this to make the plugin future-proof on Mac OS.

Thanks a lot for any help. (if of help I can also share more screenshots, projects, etc.)

**Comment by keijiro** [comment]
> On my MacBook Pro 2019

Does it have a GPU?

**Comment by Dennis123121x2** [comment]
No external gpu. As it comes from apple it has a dedicated „Radeon Pro 560X - 4 GB GDDR5“ Graphicscard. Whereas the ARM architecture of the M1 (and i also the following M2…) have a „gpu“ compartment within the CPU and therefore no stand-alone graphics card. This switch in components is when used appropriately by the software very efficient and powerful.

But it can become an issue, e.g. Agisoft Methashape can do it‘s calculations on the grapfhics card or the cpu. The graphics card used to be faster (in the case of macbook pros pre M1) but with the new M1 the workload needs to be distributed to the cpu.

**Comment by keijiro** [comment]
Radeon Pro 560X is better than M1.

**Comment by Dennis123121x2** [comment]
In most software the M1 is better. Premiere Pro and Adobe in general is much faster, agisoft if used correctly also 2x speed. Unity with mesh works just fine with the M1.

**Comment by keijiro** [comment]
In some cases, M1 beats Radeon. In some other cases, Radeon beats M1.

Could you submit a new issue if you find a case that's clearly thought to be a regression on Apple Silicon? Please don't reuse this closed case for further discussion.

**Comment by Dennis123121x2** [comment]
ok, thanks for the discussion. 
Too bad I can't describe the issue better. But a small workaround for those who encounter the same troubles. It helps if the "Outline Selection" is deselected (see screenshot). This "outline selection" seems to malfunction and slow down the navigation in the scene, if not visible this helps. 

<img width="882" alt="Bildschirmfoto 2022-12-09 um 10 50 56" src="https://user-images.githubusercontent.com/16954347/206675028-0de76a21-f987-467d-a3cd-9af8017719fd.png">

**Comment by keijiro** [comment]
> Please **DON'T** reuse this closed case for further discussion.

I initially wrote "Please reuse", but it was wrong. Please don't reuse this thread. Create a new issue (thread) for your problem.
