### ISSUE TITLE
Lighting effect on a Point cloud.

### ISSUE THREAD

**Issue by amartiousclem** [keijiro/Pcx#89]
Hello, 
Thank you for your work. Your package is much useful.
Is there a way to make it so a point cloud is affected by a light spot the same way a classic mesh gameobject is?
I mean if the light spot is the only light source and is on the point cloud's left, the point cloud will appear illuminated only on the left side while it's right is in the dark?

PS: I'm kind of a newbie with Unity, so could you please make the explanation simple?

**Comment by keijiro** [comment]
That's technically possible but out of the scope of this repository. Please understand that Pcx is just an importer -- It helps how you import data. Your problem here is how show the data. It's a separated problem.

I'd recommend using VFX Graph to control how the data is shown. It's the most convenient way to design its look.

**Comment by keijiro** [comment]
I close this issue now as answered. Please reopen it for further problem.

**Comment by amartiousclem** [comment]
Hello again, 

I've found the works of a certain [@ruben_fro](https://twitter.com/Ruben_Fro/status/1627464413166059520) on twitter, and his point clouds seem to react to light sources as I wish them to. I've asked him about it and he told me that he does this with only a custom shader and a loader based on your work. So he doesn't use any VFX graph. But I don't think he'll want to share his shader with me... 
Do you have any idea how he may have made this work ?

**Comment by keijiro** [comment]
VFX Graph is more handy because it doesn't require shader programming.

If you know better about shader programming, it might be a better way to implement it. I'm sure that Ruben is quite good at it.
