### ISSUE TITLE
Modifyng Geometry Shader

### ISSUE THREAD

**Issue by ibilab** [keijiro/Pcx#9]
Hi, i have a limited shader/coding  knowledge and couldn't find which values should be edited to assign a different base shape to the Disk geometry shader? Like a triangle shape or other primitives? 
Thanks!

**Comment by keijiro** [comment]
You can modify here to change the shape.

https://github.com/keijiro/Pcx/blob/master/Assets/Pcx/Shaders/Disk.cginc#L72
