### ISSUE TITLE
[Question] Jitter / Window screening in VR? 

### ISSUE THREAD

**Issue by wes-kay** [keijiro/Pcx#93]
There seems to be a ton of jitter in VR (quest 3) and wondering if anyone has any idea what the solution is?

https://github.com/keijiro/Pcx/assets/40011470/01ed57d6-e55d-4ab4-98e0-3da63dad3c6f

**Comment by keijiro** [comment]
You can use Discussions for questions. Please reopen it if you find a bug to be fixed.

https://github.com/keijiro/Pcx/discussions
