### ISSUE TITLE
Question: Importing Point Cloud at Runtime

### ISSUE THREAD

**Issue by Cilmering** [keijiro/Pcx#97]
Hi! I love this package, it has been immensely useful, thank you so much for creating it! But recently, I've been trying to figure out how to use the scripts in this package to render a point cloud .ply file at runtime. I already have scripts for selecting a file at runtime and grabbing its memory stream, but I haven't quite figured out which parts of your scripts I can use or adjust to allow them to take that memory stream and render it as a point cloud. I was simply wondering if you had any ideas on what areas I should look at in order to accomplish this. Thank you so much for any help you can give me!

**Comment by keijiro** [comment]
Please check #46
